[log]
level = "info" # off, error, warn, info, debug, trace

[timings]
arp_sender_timeout="30"
arp_scan_duration="60"

[notifications]
method="pushover" # For now just pushover, you can set this to "none" to avoid sending notifications (it will just log)

[notifications.pushover]
token="" # Your pushover token goes here, just copy&paste from their website after creating the app
user_key="" # User key goes here, this is the account wide code for pushover
