[database]
path="./oott.db"

[networking]
interface = "wlp3s0" # Network interface to use for scans

[log]
level = "debug" # off, error, warn, info, debug, trace

[timings]
wait_between_scans="30m" # Wait time between scans. This does not include the scan time
arp_sender_timeout="1m" # If the ARP sender process takes longer than this it will be stopped (for a class C network - 254 IPs - it should take less than a minute)
arp_scan_duration="2m" # How long to wait for response packets on each scan (5m to 10m is a good timeframe for a class B or C network)

[notifications]
# method="pushover" # For now just pushover, you can set this to "none" to avoid sending notifications (it will just log)
method="none"
notify_when_not_seen_for="1w" # Send a notification if a device comes back online after not being seen for this timeframe

[notifications.pushover]
token="a7vxi8b24ncdmuyt65x7zytkxaozi3" # Your pushover token goes here, just copy&paste from their website after creating the app
user_key="u872udy8xc8ceys9ee6iur229xs3fj" # User key goes here, this is the account wide code for pushover
